apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: example-entry
  namespace: example-namespace
spec:
  hosts:
  - "*.example.com"
  ports:
  - number: 80
    name: example-http
    protocol: HTTP
  location: MESH_INTERNAL
  resolution: DNS
  endpoints:
  - address: example.example-namespace.svc.cluster.local
